### ISSUE TITLE
Name disambiguation

### ISSUE THREAD

**Issue by aurielfournier** [embruna/refnet2#28]
AND one more thing…

7) Something Auriel mentioned yesterday has been floating around my head for a while but the penny only dropped today.

The disambiguation algorithm seems to do really well at putting different spellings of the same person in the right bins (and indicating which ones are close for users to 2x)..  

BUT

Are there any steps built in for trying to identify if  different people with the same name? If they didn’t have different ORCIDS, would we know Robert Smith and Robert Smith were actually 2 different people, given the name similarity is 100%?

I have a vague memory that we discussed this before…did we? I think we did. If not I am not sure of the best approach, In the past I have used Country, University, and State to guide me…but it was for fewer names.

**Comment by birderboone** [comment]
Thinking this through, it will auto assign robert smith the same ID only because its exactly the same name in a character matching sense. If it was any slight iteration (middle names, middle initials, short first names) it would go through the algorithm and then eventually run jarowinkler on it. I think you're right there should be a single line put in that says 'well only auto match the same names IF they have a middle name./initial'. If we're not worried about people changing universities we can do something where we auto-reject suggested matchings if the zipcode/town dont match. That would significantly cut down on the name matching people have to go through by hand.

**Comment by birderboone** [comment]
Ok. I retooled read_authors to handle this. Here's what ive got so far, though it needs to be commented better in the code. It gets kind of complicated, but i'll try my best to summarize it:

First
I match by the obvious IO or RI

Second if still unmatched
I match authors by first name and last name. After that they must meet atleast ONE of the criteria:
1. If they have a middle name it must match.
2. If they have a university affiliation it must match
3. If they have an email it must match
These selections are automatically matched with no further analysis necessary

Third if still unmatched
If none of these conditions were met. It will then run Jaro Winkler on a subset of that data that meets the following criteria:
1. First initials must match
2. If it has a middle initial it must match.
3. If it has a university or email they must not MISMATCH (meaning NAs are allowed)

These are complicated by the fact sometimes first initials are the only first names given.

**Comment by aurielfournier** [comment]
I think that works, as long as we are explict in the documentation that people will be IDed as seperate authors when they move institutions. Which is a kind of bias I am totally fine with, we just need to make sure it is clear to the user as well.

**Comment by embruna** [comment]
I concur - it's better to flag as potentially distinct people if they have different email address.  This looks comprehensive, so I'll give it a try.

**Comment by embruna** [comment]
OK, last night I sat down and looked over the disambiguation of the WOS2018 file. It's really good given the information available - it flags ~10% of 24100 author names for 2x. But as I was going through it I realized there were some names on the list with identical ORCID IDs or affiliations that were sneaking through.  I had my suspicion as to why, and with a few simple tweaks I think I got this number down to 4% of the names needing to be 2x.  I should emphasize it wasn't a brilliant insight or anything it just comes from having struggled with string (name) manipulation for several months last year (It may be these are already in there, and if so my apologies)

Prior to doing any comparisons - in fact, this should probably be done first in "read_references" - it is always a good idea to do some cleanup of strings as follows:

1) **Delete punctuation** ("Malhi, Y." and "Malhi, Y" were being flagged for comparison because of the period)

2) **trim leading and trailing white spaces** from strings (e.g., the same author was being flagged for comparison because of a space at the end of the ORCID ID for one of their references ("0000-0001-5763-2904 " vs. "0000-0001-5763-2904"). This is especially important for those being compared (AU, AF, OI, address, etc). If you really want to go hardcore you can also eliminate all spaces for the comparisons  to avoid the risk of spaces sneaking in between names -> "malhiy"

3) it's also a good idea to **convert everything to lower case** to ensure that capitalization errors or differences don't influence the outcome ("Malhi"=="malhi" -> FALSE)

This is quite easy to implement, and can check it out as follows:

`foo<-WOS2018_authors$authors`

Remove punctuation (here from AF), though note I'm not sure this removes hyphens AND em dashes? 
`foo$AF<-gsub('[[:punct:] ]+',' ',foo$AF)`

Remove leading and trailing white spaces from some of the columns
```
foo$AF<-trimws(foo$AF)
foo$AF<-trimws(foo$OI)
foo$AF<-trimws(foo$country)
foo$AF<-trimws(foo$address)
```
Convert names to lower case (doesn't really help post-comparison, obs)

`foo$AF<-lowerCase(foo$AF)`

If you do this it takes foo_authors from 4203 rows of 2566 unique AU names to review all the way down to 1009 rows of 335 names - many of which wouldn't even have made the list because the disambiguation algorithm would have would have caught their identical ORCID IDs or Names. You can check my math with 
```
foo<-foo %>% distinct(AF, .keep_all=TRUE)
foo<-foo %>% group_by(AU) %>% filter(n() > 1)
```

As for the algorithm itself, I think it's probably best to keep it with the current criteria and not add country or city. And I think it would be worth running on one of the published "test datasets", but for now I think think putting these tweaks in will put it almost there. Really great work - I'm impressed.

**Comment by birderboone** [comment]
So I sat down trying to figure out how best to improve the algorithm, particularly trying to increase the amount of automatic matches we do and decrease the amount of false positives.  First I realized the initial way was not 'smart'. 

To identify novel authors before we slowly built a list of 'novel' authors, every new author was matched agianst that list, and if it didnt match it became a new 'novel' author. The weakness in this is it makes the initial author of that groupid the baseline to compare to so if that author didnt have an address or an email, then subsequent authors couldnt match off that info. 

To change this we now compare every entry against every other entry, this allows Smith, John (university=University of Texas, email=js111@utexas.edu ) to match with all other john smith at UT, but also allow John smiths with just that email to match as well, regardless of the other info. However it has to be done iteratively, multiple times.

This new approach and coding actually decreased calculation time.

I tried to introduce as much logic as possible to match statements but written in a way that only likely matches would get matched. I also added lower cases and trimmed whitespaces. Heres the final result in order:

1. Match all OIs
2. Match all RIs from remaining list
3. Match all emails from remaining list
4. Match all full names from remaining list

I then filtered out all entries that only had a first name and last name but no other subsequent information to match with (middle name, university, email, address) because these entries are unmatchable without looking the paper up yourself. (These dont get matched later but do remain in the final data set)

5. We go through each remaining entry iterively, and for each entry a subset is created that had to match these rules:
-First names must match (Initials only are fine)
-Middle names must match (Initials or no middle is fine)
-Country must match (if exists)

6. I then attempted to automatch entries, where the subset must contain 1 of the following criteria:
-Middle name matches
-University matches
-Address matches (technically the short_address column)

If no auto match was found, i then ran jaro winkler on the subset created from step 5.

The result of all this, I feel is a very smart program that automatically does all the work for us, and leaves us with very little entries to compare. I ran this on the WOS2018 dataset. It created 24100 authors, Automatically matched 14,000/24000 authors, and ran jaro_winkler on only ~740 entries. And it ran the entire read_authors() in just under 5 minutes on my computer. Not too bad.

I know the process is very thick, as adding all the logic makes things very complicated. But I invite you to look through the resulting data.frame. I think it matches quite well. sort by groupid and youll see that every entry matches based on some commonality be it university, email, or address, and creates this rather complete picture of an authors information and even where the person has moved to through the years. Particularly if they have a lot of papers to pull information from.

You'll notice I added a country requirement, the reason for this is that I was having a lot of jaro-winkler being run on people from completely different countries, and there was very little information to prove those people were the same. I could easily take that out, but it really decreased the amount of illogical jaro_winkler matches. I know authors move to different countries, and we can still have them matched together given they have some other novel piece of information like RI, OI, email to help us out.

Let me know what you think. The big update definitely means something could be messed up.

**Comment by embruna** [comment]
I think this sounds really cool.  I wouldn't worry about all the steps, since any attempt to do this will have to do lots of different comparisons. The time savings look huge! Will try right now.

**Comment by embruna** [comment]
Really, the new version is much faster and I think much better. Using WOS 2018 I did notice a couple of things:

a) Oliveira, PE and Oliveira PS are both being assigned to group 132
b) Laurance, WE and Laurance, WF and Laurance, SGW are all being put in group 312 even though WE and WF have different middle initials and SGW has completely different first/middle initials. 

There may be others. 

Based on the order above, it seems like some these should be caught when comparing the middle initials, no? Anyway, maybe we can talk this out over skype. Seems like some tweaking and then it's good to go.

**Comment by birderboone** [comment]
This is a really complicated question. As far as I can tell the code is working exactly as I inteded it to work. Youre just bringing up good points about the difficulties of introducing so much AI into the works to limit the amount of actual thinking by users.

1.a) Oliveira, PE is getting matched to Oliveria, P (with an OI ID), who matches the Oliveria, PS because of a prioir OI ID match as well. This is the problem with trying to use all the information we can gather within each 'group' to inform us on future matching. If theres a lot of mixed up info it can create a complex 'group' that isn't perfect. Ive run into more complex group structures than Oliveria and they're hard to make the code work through intelligently.

1.b) is simply because of how unexact the email matching is. We dont match emails to people based on actually knowing whose email is who but by running jaro winkler on it. And those two authors are probably married or are related somehow beacuse they publish frequently together. Because of this, the emails get matched to either name at various times (beacuse the last names match to the email which results in a high match value). This creates a hodge podge of logic where Laurance, WE sometimes gets given the email laurence@someinstitution.edu, and other times Laurance SWG gets matched to that same email. The algorithm then matches either name just based on last name, first name, and email.

I think I could vote we have a stage where in the code we go back through and check that if after all this fancy logic a group has an assortment of names like the ones you pointed out. If that is the case we just split the entire complex BACK to their original IDs. Resulting in NONE of the names matching because the situation is too complex.

Its abit like you cant win both games. If you do stupid matching with no AI, you get too many unmatched names and your list of hand matching authors becomes too long. But if you try to introduce more AI you result in some complicated situations where names get matched together falsely occasionally. In our case the AI is atleast trying to think and there certainly IS a 'smart' reason its matching things, but it runs into strange situations like this one we cant resolve.

This is a great topic, and through text it really is hard to explain fully. I apologize if this entry was more confusing. I admit name matching large complexes of people to find 'common groups' is hard but I think we've gotten to a very cool place with the code so far. 

2.) I wrote a long explanation about why some Malhis arent being matched, but then I realized I think you're actually refering to a different problem. If you're refering to the author output, the one that needs to be hand checked. If thats the case, I had that file retain the entry that jaro winkler was run on AND every entry that also has that groupID. This is simply because the group contains all the extra assortment of information. Some entries will have a university, some an address, some an OI, some an email, etc, and this collection of information might help the user figure out if that entry belongs in the group. At the same time, I understand that by including every member of that group it would confuse users who think they have to hand check ALL THE ENTRIES. When in reality they're only checking entries that have a similarity score. It can be reverted to only include those entries inwhich jaro winkler was actually run on, I just go back and forth on whats more useful. 

I'd be up for a skype chat to go through this more, however, not until after I move to my new job with Mathieu Basille in Fort Lauderdale August 9th (YAY jobs! Thank you so much for your kind words!!)

**Comment by embruna** [comment]
Yeah, lets skype. Like I said, this is really great - I'm just trying to fine-tune around the edges. 

1) I hadn't thought about emails - maybe they should only be  used as a tie-breaker late in the process, and even then only if there is an exact name and exact email match - nothing based on similarity. 
 
2) I wonder how much the order in which the comparisons are done "channels" names into groups they can't be pulled from. In other words, middle initial isn't checked until almost the end, and by that time Laurance SG and Laurance WF are already "locked in" as members of the same group. 

What if middle initial were checked earlier on? In other words, what if the first grouping were based on last name, then first initial, then middle initial, then ORCID and the other stuff.    

Say there are 5 names: Laurance WF, Laurance WE, Laurance W, Laurance SG, Boone, M
Grouping by last name splits out Boone, M, leaving you:

Laurance WF
Laurance W
Laurance WE
Laurance SG

Comparing first initial splits out Laurance SG, leaving you 

Laurance WF
Laurance W
Laurance WE

Comparing middle initial splits out Laurance WE and Laurance WF, leaving you with a decision about 

Laurance W

For which you can then try and use the other information to assign back into one of the prior groups or keep it on its own.  

My guess is this would be slower.
